version: "3"

services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: webshop
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app

volumes:
  db-data:

networks:
  app: